project:
  type: website

website:
  title: "ML project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: ML_notebook.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



